sequenceDiagram
    Actor Client
    participant AccountService
    participant ICalendar
    participant ITransactionRepository
    participant PrintableStatement
    participant PrintableLine
    participant IBankStatementPrinter
    
    
    Client->>+AccountService: withdraw/deposit(amount)
    AccountService->>+ICalendar: CurrentDate
    AccountService->>+ITransactionRepository: Add(new Transfer(date, -amount))
    
    Client->>+AccountService: printStatement()
    AccountService->>+ITransactionRepository: AllTransactions()
    
    AccountService->>+PrintableStatement: Create(transactions)
    loop For each transaction
        PrintableStatement->>PrintableStatement: Add(transaction)
        PrintableStatement->>PrintableLine: new PrintableLine(transaction, balance)
    end
    
    AccountService->>+PrintableStatement: MakeStatement()
    
    AccountService->>+IBankStatementPrinter: Print(statment)